### ISSUE TITLE
Log-enricher profile not found error

### ISSUE THREAD

**Issue by pradeepjairamani** [kubernetes-sigs/security-profiles-operator#1103]
#### What happened:
I tried using the log-enricher for profile recording with the below configuration

`apiVersion: security-profiles-operator.x-k8s.io/v1alpha1
kind: ProfileRecording
metadata:
  name: test-recording
  namespace: security-profiles-operator
spec:
  kind: SeccompProfile
  recorder: logs
  podSelector:
    matchLabels:
      app: my-app
`

```
apiVersion: v1
kind: Pod
metadata:
  name: my-pod
  namespace: security-profiles-operator
  labels:
    app: my-app
spec:
  containers:
    - name: nginx
      image: quay.io/security-profiles-operator/test-nginx:1.19.1
    - name: redis
      image: quay.io/security-profiles-operator/redis:6.2.1

```

#### What you expected to happen:
Profile being recorded but I am facing profile not found error
`Events:
  Type     Reason     Age               From               Message
  ----     ------     ----              ----               -------
  Normal   Scheduled  29s               default-scheduler  Successfully assigned security-profiles-operator/my-pod to ip.ap-south-1.compute.internal
  Normal   Pulled     2s (x5 over 28s)  kubelet            Container image "quay.io/security-profiles-operator/test-nginx:1.19.1" already present on machine
  Warning  Failed     2s (x5 over 28s)  kubelet            Error: failed to generate security options for container "nginx": failed to generate seccomp security options for container: cannot load seccomp profile "/var/lib/kubelet/seccomp/operator/security-profiles-operator/log-enricher-trace.json": open /var/lib/kubelet/seccomp/operator/security-profiles-operator/log-enricher-trace.json: no such file or directory
  Normal   Pulled     2s (x5 over 28s)  kubelet            Container image "quay.io/security-profiles-operator/redis:6.2.1" already present on machine
  Warning  Failed     2s (x5 over 28s)  kubelet            Error: failed to generate security options for container "redis": failed to generate seccomp security options for container: cannot load seccomp profile "/var/lib/kubelet/seccomp/operator/security-profiles-operator/log-enricher-trace.json": open /var/lib/kubelet/seccomp/operator/security-profiles-operator/log-enricher-trace.json: no such file or directory`
#### How to reproduce it (as minimally and precisely as possible):
using this: https://github.com/kubernetes-sigs/security-profiles-operator/blob/main/installation-usage.md#log-enricher-based-recording

#### Environment:

Environment:
EKS
Container runtime: docker
OS (e.g: cat /etc/os-release):
NAME="Amazon Linux"
VERSION="2"
ID="amzn"
ID_LIKE="centos rhel fedora"
VERSION_ID="2"
PRETTY_NAME="Amazon Linux 2"
ANSI_COLOR="0;33"
CPE_NAME="cpe:2.3⭕amazon:amazon_linux:2"
HOME_URL="https://amazonlinux.com/"
Kernel (e.g. uname -a): 5.4.196-108.356.amzn2.x86_64 Implement minimal valuable implementation  #1 SMP Thu May 26 12:49:47 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
Others:
