### ISSUE TITLE
How to define logenricher by default while deployment of SPO 

### ISSUE THREAD

**Issue by pradeepjairamani** [kubernetes-sigs/security-profiles-operator#1167]
I am trying to configure enablelogEnricher: true configuration directly into the security-profiles-operator deployment YAML so I don't have to patch changes during runtime, can anyone help me how can I configure it (I am deploying directly through ArgoCD), 

Also will there be any issues if I add ProfileRecording with the operator deployment YAML

```
apiVersion: security-profiles-operator.x-k8s.io/v1alpha1
kind: ProfileRecording
metadata:
  name: demo-recorder
spec:
  kind: SeccompProfile
  recorder: logs
  podSelector:
    matchLabels:
      app: demo

```
