### ISSUE TITLE
merging of SELinux policies produces duplicates

### ISSUE THREAD

**Issue by jhrozek** [kubernetes-sigs/security-profiles-operator#1256]
<!-- Please use this template while reporting a bug and provide as much info as possible. Not doing so may result in your bug not being addressed in a timely manner. Thanks!

If the matter is security related, please disclose it privately via https://kubernetes.io/security/
-->

#### What happened:
I was recording File Integrity Operator policies using the SELinux log-enricher based recorder and the resulting merged policy has a ton of duplicates:
```
spec:                                                                                                                                                                                                                                         
  allow:                                                                                                                                                                                                                                      
    NetworkManager_etc_rw_t:                                                                                                                                                                                                                  
      dir:                                                                                                                                                                                                                                    
      - read                                                                                                                                                                                                                                  
      - read                                                                                                                                                                                                                                  
      - read                                                                                                                                                                                                                                  
      - read
```

#### What you expected to happen:
no duplicates

#### How to reproduce it (as minimally and precisely as possible):
1. create a namespace, label it for recording
2. create a profile recording
3. run FIO e2e tests there
4. delete profile recording

#### Anything else we need to know?:
I used today's git HEAD, so 0.5.0 with a bunch of minor patches

#### Environment:

- Cloud provider or hardware configuration: AWS
- OS (e.g: `cat /etc/os-release`): RHCOS
- Kernel (e.g. `uname -a`): N/A
- Others: N/A
