### ISSUE TITLE
Flatcar VM bootstrap fails

### ISSUE THREAD

**Issue by saschagrunert** [kubernetes-sigs/security-profiles-operator#1377]
The CI test fails across all branches: https://github.com/kubernetes-sigs/security-profiles-operator/actions/runs/3680636245/jobs/6232228689

```
    default: [kubelet-check] It seems like the kubelet isn't running or healthy.
    default: [kubelet-check] The HTTP call equal to 'curl -sSL http://localhost:10248/healthz' failed with error: Get "http://localhost:10248/healthz": dial tcp [::1]:10248: connect: connection refused.
    default: 
    default: Unfortunately, an error has occurred:
    default: 	timed out waiting for the condition
    default: 
    default: This error is likely caused by:
    default: 	- The kubelet is not running
    default: 	- The kubelet is unhealthy due to a misconfiguration of the node in some way (required cgroups disabled)
    default: 
    default: If you are on a systemd-powered system, you can try to troubleshoot the error with the following commands:
    default: 	- 'systemctl status kubelet'
    default: 	- 'journalctl -xeu kubelet'
    default: 
    default: Additionally, a control plane component may have crashed or exited when started by the container runtime.
    default: To troubleshoot, list all containers using your preferred container runtimes CLI.
    default: Here is one example how you may list all running Kubernetes containers by using crictl:
    default: 	- 'crictl --runtime-endpoint unix:///run/containerd/containerd.sock ps -a | grep kube | grep -v pause'
    default: 	Once you have found the failing container, you can inspect its logs with:
    default: 	- 'crictl --runtime-endpoint unix:///run/containerd/containerd.sock logs CONTAINERID'
    default: error execution phase wait-control-plane: couldn't initialize a Kubernetes cluster
    default: To see the stack trace of this error execute with --v=5 or higher
The SSH command responded with a non-zero exit status. Vagrant
assumes that this means the command failed. The output for this command
should be in the log above. Please read the output to determine what
went wrong.
make: *** [vagrant-up-flatcar] Error 1
```
