### ISSUE TITLE
Possible to use baseProfileName from single profile (non-namespaced)

### ISSUE THREAD

**Issue by kecebon9** [kubernetes-sigs/security-profiles-operator#1448]
#### What would you like to be added:

Currently when using `baseProfileName`, we only able to unioned with the profile on the same namespace. 
Possible if we can use `baseProfileName` from non-namespaced as global base profile?

#### Why is this needed:

In the multi user environment, it's easier to manage single seccomp profiles (base profile) as baseline. When specific user (from different namespace) need to customize their seccomp profiles, it need to inherit from the base profile as their baseline.
In current setting, we need to create the base profile on every namespace, so they can use it in `baseProfileName`

Thank you

**Comment by saschagrunert** [comment]
Hey @kecebon9, that's an interesting enhancement. I'm not exactly sure how we would differentiate the base profiles. Maybe we just lookup in all managed namespaces for base profiles. @kubernetes-sigs/security-profiles-operator-maintainers what are your thoughts on that?

**Comment by JAORMX** [comment]
What if we allow a profile to be "public" via an annotation? This way, a central team could mark some base profiles to be public and they'd be replicated to other namespaces.

Underneath, we could have a controller that makes sure that the replicated profiles are read only and stay in the desired state (the same profile as the managed, original one). And we could even apply optimizations on the daemon side to optimize storage (symlinks to the original policy file on disk?).

Just an idea.

**Comment by kecebon9** [comment]
Hi @saschagrunert @JAORMX 
Thanks for the attention
Does it possible to use `baseProfileName` to refer from another namespace something like below:

```
---
apiVersion: security-profiles-operator.x-k8s.io/v1beta1
kind: SeccompProfile
metadata:
  namespace: security-profiles-operator
  name: base-profile
spec:
  defaultAction: SCMP_ACT_ALLOW
  syscalls:
  - action: SCMP_ACT_ERRNO
    names:
    - ptrace

---
apiVersion: security-profiles-operator.x-k8s.io/v1beta1
kind: SeccompProfile
metadata:
  namespace: namespace1
  name: svc1-profile
spec:
  defaultAction: SCMP_ACT_ERRNO
  baseProfileName: security-profiles-operator/base-profile
  syscalls:
  - action: SCMP_ACT_ALLOW
    names:
    - uname
    - ...
```
