### ISSUE TITLE
ProfileBinding not working

### ISSUE THREAD

**Issue by kecebon9** [kubernetes-sigs/security-profiles-operator#1462]
#### What happened:

Somehow the profile binding is not working, i tried to destroy my local k8s, no luck. Any idea if i'm doing it wrong?

#### What you expected to happen:

The security context should have seccomp profile attached
```
⇒ kubectl get pod hello -o jsonpath='{.spec.containers[*].securityContext.seccompProfile}'
{"localhostProfile":"operator/default/profile-complain-unsafe.json","type":"Localhost"}      
```

#### How to reproduce it (as minimally and precisely as possible):
Install SPO
```
kubectl apply -f https://github.com/cert-manager/cert-manager/releases/download/v1.10.1/cert-manager.yaml
kubectl apply -f https://raw.githubusercontent.com/kubernetes-sigs/security-profiles-operator/main/deploy/operator.yaml

# tried to use old one, also the same result
kubectl apply -f https://raw.githubusercontent.com/kubernetes-sigs/security-profiles-operator/v0.5.0/deploy/operator.yaml
```

Apply below:
```
---
apiVersion: security-profiles-operator.x-k8s.io/v1beta1
kind: SeccompProfile
metadata:
  name: profile-complain-unsafe
spec:
  defaultAction: "SCMP_ACT_LOG"
---
apiVersion: security-profiles-operator.x-k8s.io/v1alpha1
kind: ProfileBinding
metadata:
  name: hello-binding
spec:
  profileRef:
    kind: SeccompProfile
    name: profile-allow-unsafe
  image: quay.io/security-profiles-operator/test-hello-world:latest
---
apiVersion: v1
kind: Pod
metadata:
  name: hello
spec:
  containers:
  - image: quay.io/security-profiles-operator/test-hello-world:latest
    name: hello
    resources: {}
    securityContext:
      allowPrivilegeEscalation: false
      capabilities:
        drop:
        - ALL
      runAsUser: 1000
      runAsNonRoot: true
  restartPolicy: Never
```

The output
```
⇒ kubectl apply -f binding.yaml   
seccompprofile.security-profiles-operator.x-k8s.io/profile-complain-unsafe created
profilebinding.security-profiles-operator.x-k8s.io/hello-binding created
pod/hello created

⇒ kubectl describe profilebinding 
Name:         hello-binding
Namespace:    default
Labels:       <none>
Annotations:  <none>
API Version:  security-profiles-operator.x-k8s.io/v1alpha1
Kind:         ProfileBinding
Metadata:
  Creation Timestamp:  2023-02-07T03:48:07Z
  Generation:          1
  Managed Fields:
    API Version:  security-profiles-operator.x-k8s.io/v1alpha1
    Fields Type:  FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          .:
          f:kubectl.kubernetes.io/last-applied-configuration:
      f:spec:
        .:
        f:image:
        f:profileRef:
          .:
          f:kind:
          f:name:
    Manager:         kubectl-client-side-apply
    Operation:       Update
    Time:            2023-02-07T03:48:07Z
  Resource Version:  1151
  UID:               e76b4cfd-17a0-4474-8520-3e07b8c8dd6c
Spec:
  Image:  quay.io/security-profiles-operator/test-hello-world:latest
  Profile Ref:
    Kind:  SeccompProfile
    Name:  profile-allow-unsafe
Events:    <none>

⇒ kubectl get pod hello -o jsonpath='{.spec.containers[*].securityContext.seccompProfile}'
⇒

⇒ kubectl describe pod hello                     
Name:         hello
Namespace:    default
Priority:     0
Node:         kind-worker/1.1.1.1
Start Time:   Tue, 07 Feb 2023 11:48:07 +0800
Labels:       <none>
Annotations:  <none>
Status:       Succeeded
IP:           1.1.1.1
IPs:
  IP:  1.1.1.1
Containers:
  hello:
    Container ID:   containerd://c9129257d1a2e4e8077b61116f154efcd624e01717749f44306d0831619a52de
    Image:          quay.io/security-profiles-operator/test-hello-world:latest
    Image ID:       quay.io/security-profiles-operator/test-hello-world@sha256:66ce924069ec4181725d15aa27f34afbaf082f434f448dc07a42daa3305cdab3
    Port:           <none>
    Host Port:      <none>
    State:          Terminated
      Reason:       Completed
      Exit Code:    0
      Started:      Tue, 07 Feb 2023 11:48:14 +0800
      Finished:     Tue, 07 Feb 2023 11:48:14 +0800
    Ready:          False
    Restart Count:  0
    Environment:    <none>
    Mounts:
      /var/run/secrets/kubernetes.io/serviceaccount from kube-api-access-hjx99 (ro)
Conditions:
  Type              Status
  Initialized       True 
  Ready             False 
  ContainersReady   False 
  PodScheduled      True 
Volumes:
  kube-api-access-hjx99:
    Type:                    Projected (a volume that contains injected data from multiple sources)
    TokenExpirationSeconds:  3607
    ConfigMapName:           kube-root-ca.crt
    ConfigMapOptional:       <nil>
    DownwardAPI:             true
QoS Class:                   BestEffort
Node-Selectors:              <none>
Tolerations:                 node.kubernetes.io/not-ready:NoExecute op=Exists for 300s
                             node.kubernetes.io/unreachable:NoExecute op=Exists for 300s
Events:
  Type    Reason     Age    From               Message
  ----    ------     ----   ----               -------
  Normal  Scheduled  5m12s  default-scheduler  Successfully assigned default/hello to kind-worker
  Normal  Pulling    5m12s  kubelet            Pulling image "quay.io/security-profiles-operator/test-hello-world:latest"
  Normal  Pulled     5m5s   kubelet            Successfully pulled image "quay.io/security-profiles-operator/test-hello-world:latest" in 6.616362366s
  Normal  Created    5m5s   kubelet            Created container hello
  Normal  Started    5m5s   kubelet            Started container hello
```

#### Anything else we need to know?:

- kind version 0.11.1
- k8s version v1.22.15

#### Environment:

- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`): Ubuntu 20.04
- Kernel (e.g. `uname -a`): 5.14.0-1056
- Others:
