### ISSUE TITLE
Decide whether and how to add default syscalls to the SeccompProfile CRD

### ISSUE THREAD

**Issue by cmurphy** [kubernetes-sigs/security-profiles-operator#150]
Part of the idea of #117 was to perhaps ensure that a standard set of default syscalls were present in a profile so that a minimum viable pod could be launched in kubernetes on e.g. runc. This issue is to evaluate whether this is worthwhile and discuss how to implement it.

The first consideration is that it's possible that the syscalls used by runc could change over time, and in fact they haven't been fully documented (https://github.com/opencontainers/runc/issues/2097) so we would need to maintain our own list. Moreover, a container runtime other than runc might be used, and container managers on top of runc like docker/cri-o might also call other syscalls. Also, the list might be different depending on the architecture.

Another consideration is the pause container, which seems to use an additional set of syscalls on top of what is required for runc. Should those syscalls be included in the defaults?

Finally, the actions to take for a syscall aren't a blanket "allow" or "deny", there is also e.g. "log", "trace", "kill", etc. If a user creates a complex profile with different actions for different syscalls, should the default syscalls use the "allow" action or the "log" action? What happens if the user adds one of the default syscalls to their "log" rule, but the controller is automatically adding it to the "allow" rule?

One idea could be to simply maintain an example SeccompProfile that contains the minimum required syscalls instead of building it into the CRD/controller. Thoughts?

**Comment by saschagrunert** [comment]
I agree this is a though topic. Maybe we could start with documentation around that topic and explain to the user:

- Which syscalls are going to be expected by nearly every workload, because they're required by the OCI runtime (like runc)
- Which syscalls are additionally required, for example to run `kubectl exec -it …`

We could scope the documentation on an x86_64 environment and describe that this will differ on different architectures.

Adding the minimal example as well as an e2e test around it seems like a good idea, too. We can show to the user how to use that minimal profile as a starting base for profile development. And that brings me to the next question: Would it be possible to stack/combine two profiles now that we have a CRD? We could define a new field `baseProfile` for a CRD and afterwards just merge them together and write it on disk, right?

**Comment by cmurphy** [comment]
> Would it be possible to stack/combine two profiles now that we have a CRD? We could define a new field baseProfile for a CRD and afterwards just merge them together and write it on disk, right?

I think that could work...so it would look something like this:

```
---
kind: SeccompProfile
metadata:
  name: base
spec:
  defaultAction: SCMP_ACT_ERRNO
  syscalls:
  - action: SCMP_ACT_ALLOW
    names:
    - capget
    - ...
---
kind: SeccompProfile
metadata:
  name: hello-world
spec:
  baseProfile: base
  targetWorkload: hello
  syscalls:
  - action: SCMP_ACT_ALLOW
    names:
    - arch_prctl
    - ...
  - action: SCMP_ACT_LOG
    names:
    - pause
    - ...
```
/var/lib/kubelet/seccomp/operator/default/hello/hello-world.json:
```
{
  "defaultAction": "SCMP_ACT_ERRNO",
  "syscalls": [
    {
      "action": "SCMP_ACT_ALLOW",
      "names": ["capget", "arch_prctl", ...]
    },
    {
      "action": "SCMP_ACT_LOG",
      "names": ["pause", ...]
    }
  ]
}
```

Still, what should happen if there are syscalls with different actions in the base versus user-defined profile? e.g.

base:
```
  syscalls:
  - action: SCMP_ACT_ALLOW
    names:
    - capget
```
user-defined:
```
  syscalls:
  - action: SCMP_ACT_ERRNO
    names:
    - capget
```
merged:
```
...
  "syscalls": [
    {
      "action": "SCMP_ACT_ALLOW",
      "names": ["capget",...]
    },
    {
      "action": "SCMP_ACT_ERRNO",
      "names": ["capget", ...]
    }

```

That would be an invalid profile, I think? But I guess no different than if the user had created just a single invalid profile...
