### ISSUE TITLE
Update SPOD failed: host-proc-volume not found

### ISSUE THREAD

**Issue by fert-f** [kubernetes-sigs/security-profiles-operator#1645]
#### How to reproduce it (as minimally and precisely as possible):

1. Install SPO using helm:
```
helm upgrade --install security-profiles-operator \
  --namespace security-profiles-operator https://github.com/kubernetes-sigs/security-profiles-operator/releases/download/v0.8.0/security-profiles-operator-0.8.0.tgz \
  --set spoImage.tag=v0.8.0 \
  --set verbosity="1"
```
2. enable recorders:
```
kubectl -n security-profiles-operator patch spod spod --type=merge -p '{"spec":{"enableBpfRecorder":true}}'
OR
kubectl -n security-profiles-operator patch spod spod --type=merge -p '{"spec":{"enableLogEnricher":true}}'
```
4. Got error at SPOD CRD:
```
Warning  CannotUpdateSPOD  5m57s  spod-config  updating operator DaemonSet: DaemonSet.apps "spod" is invalid: [spec.template.spec.volumes[18].hostPath.path: Required value, spec.template.spec.containers[1].volumeMounts[3].name: Not found: "host-proc-volume"]
```

#### Environment:
- Virtualbox
- OS (e.g: `cat /etc/os-release`): Ubuntu 22.04.2 LTS
- Kernel (e.g. `uname -a`): 5.15.0-69-generic
- Others: Kubernetes v1.22.15

<details>
  <summary>Current SPOD Daemonset</summary>
Neat yaml:

```yaml
apiVersion: apps/v1
kind: DaemonSet
metadata:
  annotations:
    deprecated.daemonset.template.generation: "3"
  name: spod
  namespace: security-profiles-operator
spec:
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: security-profiles-operator
      name: spod
  template:
    metadata:
      annotations:
        openshift.io/scc: privileged
      creationTimestamp: null
      labels:
        app: security-profiles-operator
        name: spod
    spec:
      containers:
      - args:
        - daemon
        - --with-recording=false
        env:
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: spec.nodeName
        - name: OPERATOR_NAMESPACE
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
        - name: SPOD_NAME
          value: spod
        - name: KUBELET_DIR
          value: /var/lib/kubelet
        - name: HOME
          value: /home
        - name: SPO_VERBOSITY
          value: "1"
        image: gcr.io/k8s-staging-sp-operator/security-profiles-operator:latest
        imagePullPolicy: Always
        livenessProbe:
          failureThreshold: 1
          httpGet:
            path: /healthz
            port: liveness-port
            scheme: HTTP
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        name: security-profiles-operator
        ports:
        - containerPort: 8085
          name: liveness-port
          protocol: TCP
        resources:
          limits:
            ephemeral-storage: 200Mi
            memory: 128Mi
          requests:
            cpu: 100m
            ephemeral-storage: 50Mi
            memory: 64Mi
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
          readOnlyRootFilesystem: true
          runAsGroup: 65535
          runAsUser: 65535
          seLinuxOptions:
            type: spc_t
          seccompProfile:
            localhostProfile: security-profiles-operator.json
            type: Localhost
        startupProbe:
          failureThreshold: 10
          httpGet:
            path: /healthz
            port: liveness-port
            scheme: HTTP
          periodSeconds: 3
          successThreshold: 1
          timeoutSeconds: 1
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /var/lib/kubelet/seccomp/operator
          name: host-operator-volume
        - mountPath: /etc/selinux.d
          name: selinux-drop-dir
        - mountPath: /var/run/selinuxd
          name: selinuxd-private-volume
        - mountPath: /tmp/security-profiles-operator-recordings
          name: profile-recording-output-volume
        - mountPath: /var/run/grpc
          name: grpc-server-volume
        - mountPath: /home
          name: home-volume
        - mountPath: /tmp
          name: tmp-volume
      - args:
        - --secure-listen-address=0.0.0.0:9443
        - --upstream=http://127.0.0.1:8080
        - --v=10
        - --tls-cert-file=/var/run/secrets/metrics/tls.crt
        - --tls-private-key-file=/var/run/secrets/metrics/tls.key
        image: gcr.io/kubebuilder/kube-rbac-proxy:v0.14.0
        imagePullPolicy: IfNotPresent
        name: metrics
        ports:
        - containerPort: 9443
          name: https
          protocol: TCP
        resources:
          limits:
            ephemeral-storage: 20Mi
            memory: 128Mi
          requests:
            cpu: 50m
            ephemeral-storage: 10Mi
            memory: 32Mi
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /var/run/secrets/metrics
          name: metrics-cert-volume
          readOnly: true
      dnsPolicy: ClusterFirst
      initContainers:
      - args:
        - non-root-enabler
        - --runtime=
        env:
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: spec.nodeName
        - name: KUBELET_DIR
          value: /var/lib/kubelet
        - name: SPO_VERBOSITY
          value: "1"
        image: gcr.io/k8s-staging-sp-operator/security-profiles-operator:latest
        imagePullPolicy: Always
        name: non-root-enabler
        resources:
          limits:
            ephemeral-storage: 50Mi
            memory: 64Mi
          requests:
            cpu: 100m
            ephemeral-storage: 10Mi
            memory: 32Mi
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            add:
            - CHOWN
            - FOWNER
            - FSETID
            - DAC_OVERRIDE
            drop:
            - ALL
          readOnlyRootFilesystem: true
          runAsUser: 0
          seLinuxOptions:
            type: spc_t
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /var/lib
          name: host-varlib-volume
        - mountPath: /opt/spo-profiles
          name: operator-profiles-volume
          readOnly: true
        - mountPath: /host
          name: host-root-volume
        - mountPath: /var/run/secrets/metrics
          name: metrics-cert-volume
      nodeSelector:
        kubernetes.io/os: linux
      priorityClassName: system-node-critical
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext:
        seccompProfile:
          type: RuntimeDefault
      serviceAccount: spod
      serviceAccountName: spod
      terminationGracePeriodSeconds: 30
      tolerations:
      - effect: NoSchedule
        key: node-role.kubernetes.io/master
        operator: Exists
      volumes:
      - hostPath:
          path: /var/lib
          type: Directory
        name: host-varlib-volume
      - hostPath:
          path: /var/lib/security-profiles-operator
          type: DirectoryOrCreate
        name: host-operator-volume
      - configMap:
          defaultMode: 420
          name: security-profiles-operator-profile
        name: operator-profiles-volume
      - name: selinux-drop-dir
      - name: selinuxd-private-volume
      - hostPath:
          path: /sys/fs/selinux
          type: Directory
        name: host-fsselinux-volume
      - hostPath:
          path: /etc/selinux
          type: Directory
        name: host-etcselinux-volume
      - hostPath:
          path: /var/lib/selinux
          type: Directory
        name: host-varlibselinux-volume
      - hostPath:
          path: /tmp/security-profiles-operator-recordings
          type: DirectoryOrCreate
        name: profile-recording-output-volume
      - hostPath:
          path: /var/log/audit
          type: DirectoryOrCreate
        name: host-auditlog-volume
      - hostPath:
          path: /var/log
          type: DirectoryOrCreate
        name: host-syslog-volume
      - name: metrics-cert-volume
        secret:
          defaultMode: 420
          secretName: metrics-server-cert
      - hostPath:
          path: /sys/kernel/debug
          type: Directory
        name: sys-kernel-debug-volume
      - hostPath:
          path: /etc/os-release
          type: File
        name: host-etc-osrelease-volume
      - name: tmp-volume
      - name: grpc-server-volume
      - hostPath:
          path: /
          type: Directory
        name: host-root-volume
      - name: home-volume
  updateStrategy:
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 100%
    type: RollingUpdate
```

</details>
