### ISSUE TITLE
priorityClassName is ignored on initial apply of the operator

### ISSUE THREAD

**Issue by maxyeg86** [kubernetes-sigs/security-profiles-operator#1838]
#### What happened:

When running `kubectl apply -f operator.yaml` while  part of the operator.yaml looks like this (default high-priority instead of system-node-critical):

```
priorityClassName:
  default: high-priority
  description: PriorityClassName if defined, indicates the spod podpriority class.
  type: string
``` 

The default priorityClassName is ignored and the spod is created with `priorityClassName: system-node-critical`

#### What you expected to happen:

The expected behavior is that the spod will be created with the default priorityClassName as defined in the operator.yaml

#### How to reproduce it (as minimally and precisely as possible):

```
kubectl apply -f priority-class.yaml

kubectl apply -f https://github.com/cert-manager/cert-manager/releases/download/v1.12.1/cert-manager.yaml
kubectl --namespace cert-manager wait --for condition=ready pod -l app.kubernetes.io/instance=cert-manager

kubectl apply -f https://raw.githubusercontent.com/kubernetes-sigs/security-profiles-operator/main/deploy/operator.yaml
```

Files involved:

priority-class.yaml:
```
apiVersion: scheduling.k8s.io/v1
kind: PriorityClass
metadata:
  name: high-priority
value: 1000
globalDefault: false
description: "This priority class should be used for apparmor service pods only."
```

operator.yaml (The same exact file as in the git repo except for `default: high-priority` instead of `default: system-node-critical`):
```
priorityClassName:
  default: high-priority
  description: PriorityClassName if defined, indicates the spod podpriority class.
  type: string
```

#### Anything else we need to know?:

Probably happens because of a hard coded value [here](https://github.com/kubernetes-sigs/security-profiles-operator/blob/6d51dc8d1bdae339b47facd5c9b8a0e884c30ff8/internal/pkg/manager/spod/bindata/spod.go#L75) but not sure.
#### Environment:

- Cloud provider or hardware configuration: Google Kubernetes Engine
- OS (e.g: `cat /etc/os-release`): Ubuntu
- Kernel (e.g. `uname -a`): N/A
- Others:
