### ISSUE TITLE
ignore istio init container while eBPF profiling

### ISSUE THREAD

**Issue by sybadm** [kubernetes-sigs/security-profiles-operator#2007]
#### What would you like to be added:
eBPF profiling automatically start recording for istio init containers istio-proxy and istio-validation

There should be some way to ignore list of containers from applying eBPF profiles and recordings.

#### Why is this needed:
Istio service mesh is commonly used and there could be some other similar use cases to ignore a specific containers within the pod.

#### User story covered

```
$ kubectl get seccompprofiles -A
NAMESPACE                    NAME                                  STATUS      AGE
app-dvlp-i2                  app-recording-istio-proxy             Installed   5h35m
app-dvlp-i2                  app-recording-istio-validation        Installed   5h35m
seccomp                      app-audit-profile                     Installed   5h55m
security-profiles-operator   log-enricher-trace                    Installed   5h57m
```

**Comment by saschagrunert** [comment]
I think we have what you need implemented in https://github.com/kubernetes-sigs/security-profiles-operator/pull/833

Unfortunately docs are missing.

**Comment by sybadm** [comment]
Okay. SO I had look at the https://github.com/kubernetes-sigs/security-profiles-operator/pull/833

Looks like it is implemented other way round to include the container name to record

```
kind: ProfileRecording
metadata:
  name: app-recording
  namespace: app-dvlp-i2
spec:
  kind: SeccompProfile
  recorder: bpf
  podSelector:
    matchLabels:
      app: app1
containers: ["nginx"]
```

What I was looking was ignore list than include list. Include list will need to be updated everytime when new containers are deployed and requires much maintenance
