### ISSUE TITLE
the pod is in crashloopbackoff while enabling ebpf in spod

### ISSUE THREAD

**Issue by naveenthangaraj03** [kubernetes-sigs/security-profiles-operator#2780]
After editing the spod with "enableBpfRecorder: true" the spod creates daemonset with 2 container in each pod, but the bpf-recorder container is in crashloopbackoff 

The logs of the container
```
275: (b7) r4 = 0
276: (85) call unknown#181
invalid func unknown#181
processed 240 insns (limit 1000000) max_states_per_insn 0 total_states 15 peak_states 15 mark_read 7
-- END PROG LOAD LOG --
libbpf: prog 'path_mkdir': failed to load: -22
libbpf: failed to load object 'recorder.bpf.o'
E0323 08:40:40.305301 3560649 main.go:246] "running security-profiles-operator" err="bpf load: load bpf object: failed to load BPF object: invalid argument" logger="setup"
```
Hardware: Own physical server
OS : Linus(Ubuntu 22.04)
Kernel: (uname -r) 5.15.0-131-generic
Others: containerd

```
kubectl get node -o wide

NAME                            STATUS   ROLES           AGE   VERSION   INTERNAL-IP   EXTERNAL-IP   OS-IMAGE             KERNEL-VERSION       CONTAINER-RUNTIME
naveen-security-4cwd9           Ready    control-plane   10d   v1.30.9   10.8.30.25    10.8.30.25    Ubuntu 22.04.5 LTS   5.15.0-131-generic   containerd://1.7.20
naveen-securityw1-dcmq5-dwbck   Ready    <none>          10d   v1.30.9   10.8.30.59    10.8.30.59    Ubuntu 22.04.5 LTS   5.15.0-131-generic   containerd://1.7.20
naveen-securityw1-dcmq5-hdtnr   Ready    <none>          10d   v1.30.9   10.8.30.15    10.8.30.15    Ubuntu 22.04.5 LTS   5.15.0-131-generic   containerd://1.7.20

```

```
The SPOD spec

spec:
  disableOciArtifactSignatureVerification: false
  enableBpfRecorder: true
  enableMemoryOptimization: true
  enableProfiling: true
  hostProcVolumePath: /proc
  priorityClassName: system-node-critical
  selinuxOptions:
    allowedSystemProfiles:
    - container
  selinuxTypeTag: unconfined_t
  staticWebhookConfig: false
  tolerations:
  - effect: NoSchedule
    key: node-role.kubernetes.io/master
    operator: Exists
  - effect: NoSchedule
    key: node-role.kubernetes.io/control-plane
    operator: Exists
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
```

Already they raised issue with this same error 2 year back but they mentioned the error will be resolved if we update the kernel to 5.8.0 or greater but it throws error if i use the kernel 5.15.0-131-generic.
