### ISSUE TITLE
AWS EKS Support?

### ISSUE THREAD

**Issue by jwlai** [kubernetes-sigs/security-profiles-operator#2897]
Hi, 

I found this project through the AWS EKS Best Practices (https://docs.aws.amazon.com/eks/latest/best-practices/runtime-security.html). 

I'm looking to use it to profile applications so I can enforce a Seccomp Profile safely (either RuntimeDefault or something custom as needed), and I attempted to use the tool to a profile to be generated after enabling profiling and deleting the pod. But I am having some trouble, perhaps it's because I'm running on EKS?

Settings/Environment :

AWS EKS Cluster 

```
apiVersion: v1
kind: Namespace
metadata:
  labels:
    app: security-profiles-operator
    openshift.io/cluster-monitoring: "true"
    pod-security.kubernetes.io/audit: privileged
    pod-security.kubernetes.io/enforce: privileged
    pod-security.kubernetes.io/warn: privileged
  name: security-profiles-operator
```

```
apiVersion: v1
kind: Pod
metadata:
  name: test-app
  labels:
    app: test-app
  namespace: security-profiles-operator
spec:
  containers:
  - name: test-container
    image: nginx:1.23.2
```

```
---
apiVersion: security-profiles-operator.x-k8s.io/v1alpha1
kind: SecurityProfilesOperatorDaemon
metadata:
  name: spod
  namespace: security-profiles-operator
spec:
  enableSelinux: false
  enableLogEnricher: true
  enableAppArmor: false
  enableBpfRecorder: true
  enableProfiling: true
  verbosity: 1
```

```
---
apiVersion: security-profiles-operator.x-k8s.io/v1alpha1
kind: ProfileRecording
metadata:
  # The name of the Recording is the same as the resulting `SeccompProfile` CRD
  # after reconciliation.
  name: test-recording
  namespace: security-profiles-operator
spec:
  kind: SeccompProfile
  recorder: bpf
  # uncomment to merge recordings of the same containers
  # mergeStrategy: containers
  podSelector:
    matchLabels:
      app: test-app
```

spod-* pod Logs attached
[log-enricher.txt](https://github.com/user-attachments/files/20889891/log-enricher.txt)
[security-profiles-operator.txt](https://github.com/user-attachments/files/20889896/security-profiles-operator.txt)
