### ISSUE TITLE
Add test for tracing containers simultaneously

### ISSUE THREAD

**Issue by saschagrunert** [kubernetes-sigs/security-profiles-operator#324]
This can be done after the merge of https://github.com/cri-o/cri-o/pull/4544#event-4342417744 and https://github.com/cri-o/cri-o/pull/4552.

We should adapt our setup scripts to use a latest master of CRI-O and add an e2e test for recording two independent containers within a single pod:

```
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: test
spec:
  selector:
    matchLabels:
      app: test
  replicas: 1
  template:
    metadata:
      labels:
        app: test
      annotations:
        io.containers.trace-syscall/nginx: of:/tmp/nginx.json
        io.containers.trace-syscall/redis: of:/tmp/redis.json
    spec:
      containers:
        - name: nginx
          image: nginx:latest
        - name: redis
          image: redis:latest
```

Documentation around that feature may be updated, too.
