### ISSUE TITLE
Make security-profiles-operator daemonset configurable

### ISSUE THREAD

**Issue by voigt** [kubernetes-sigs/security-profiles-operator#327]
#### What would you like to be added:

A mechanism to make the creation of the security-profiles-operator daemonset configurable. At this point in time, the entire Daemonset is [hardcoded](https://github.com/kubernetes-sigs/security-profiles-operator/blob/master/internal/pkg/controllers/spod/bindata/spod.go#L45).

#### Why is this needed:

As an infrastructure SRE there are a couple of scenarios, where I'd like to change the configuration of the daemonset:

- change container image source
- change nodeselectors and tolerations
- change resource requests and limits
- securitycontexts
- ... you name it

#### User story covered

As an infrastructure SRE, Kirsti wants to make sure that common profiles are available to all users, so folks can deploy applications securely. [↗️](https://github.com/kubernetes-sigs/security-profiles-operator/blob/master/doc/user-stories.md#as-an-infrastructure-sre-kirsti-wants-to-make-sure-that-common-profiles-are-available-to-all-users-so-folks-can-deploy-applications-securely)

**Comment by voigt** [comment]
Are there any opinion how DS configuration should look like?

Here are some thoughts to get the discussion started:

If I get it correctly, there are different daemonsets per use case, which are created at runtime:
- `seccomp-spod`
- `selinux-spod`
- `recorder-spod`
- and in future something like `apparmor-spod`

I think it should be possible to configure them independently from each other. This increases flexibility for clusters with inhomogeneous nodes (e.g. some of them have AppArmor activated, some do not).

As the whole story is only about configuration on cluster resource level, I don't think a detailed configuration via flags makes sense here. Therefore I'd suggest a flag for the operator like `--config, -C` or `--resource-config, -R` which optionally references a yaml file.

The yaml file then could follow (more or less) the resource spec:

```yaml
seccomp-spod:
  spec:
    template:
      spec:
        tolerations:
        - effect: NoSchedule
          key: role
          operator: Equal
          value: infra
---
selinux-spod:
  spec:
    template:
      containers:
        - args:
            - [...]
          image: [...]
          imagePullPolicy: Always
---
recorder-spod:
...
---
apparmor-spod:
...
```

I assume this would be straight forward to parse and apply and would give a lot of freedom about the DS.

Though, with this approach comes a drawback: it would be relatively easy to break the things or make them insecure (e.g. `spec.template.spec.containers.securityContext`)...

Just some thoughts. Happy to read about your opinion!
