### ISSUE TITLE
Seccomp Profile is not deleted even when there are no pods using it

### ISSUE THREAD

**Issue by tshaiman** [kubernetes-sigs/security-profiles-operator#785]
#### What happened: Followed the Seccomp profile tutorial as its presented in the Getting Started Page.
After deleting the demo pod and the Seccomprofile , pods got deleted but the seccomprofile hangs in terminating state forever.
there are not workloads on the Cluster using that Profile ( simple AKS demo cluster)

#### What you expected to happen:
- kubectl delete Seccomprofile should delete the profile if there are no pods who uses it .
-  this is possible due to some finalizers ,but there should be no finalizer if there is no pod .

#### How to reproduce it (as minimally and precisely as possible):
- follow the tutorial steps to install "profile1"  as described here :
https://github.com/kubernetes-sigs/security-profiles-operator/blob/main/installation-usage.md#create-profile
- create the pod
- verify the pod uses the profile as explained in the tutorial
-  delete the pod
-  delete the profile 
- **BUG** : the profile is not deleted 

#### Anything else we need to know?:
view the image below : 
- no pods
- profile in Terminating state for 21h
![profile](https://user-images.githubusercontent.com/512709/150648676-7b865fa2-21d1-4d49-a1f5-d04a2b940865.png)

#### Environment:

- Azure AKS version 1.21.7
- Linux

**Comment by saschagrunert** [comment]
Hey @tshaiman, thank you for reporting this issue. I have access to azure and created a cluster like this:

```
> k get nodes -o wide
NAME                                STATUS   ROLES   AGE     VERSION   INTERNAL-IP   EXTERNAL-IP   OS-IMAGE             KERNEL-VERSION     CONTAINER-RUNTIME
aks-agentpool-27737729-vmss000000   Ready    agent   9m53s   v1.21.7   10.240.0.4    <none>        Ubuntu 18.04.6 LTS   5.4.0-1065-azure   containerd://1.4.9+azure
aks-agentpool-27737729-vmss000001   Ready    agent   9m46s   v1.21.7   10.240.0.5    <none>        Ubuntu 18.04.6 LTS   5.4.0-1065-azure   containerd://1.4.9+azure
aks-agentpool-27737729-vmss000002   Ready    agent   9m58s   v1.21.7   10.240.0.6    <none>        Ubuntu 18.04.6 LTS   5.4.0-1065-azure   containerd://1.4.9+azure
```

Unfortunately, this worked for me:

1. `kubectl apply -f https://github.com/jetstack/cert-manager/releases/download/v1.6.1/cert-manager.yaml`
2. `kubectl apply -f https://raw.githubusercontent.com/kubernetes-sigs/security-profiles-operator/main/deploy/operator.yaml`
3. Apply the profile:
```yaml
apiVersion: security-profiles-operator.x-k8s.io/v1beta1
kind: SeccompProfile
metadata:
  namespace: default
  name: profile1
spec:
  defaultAction: SCMP_ACT_LOG
```
4. Apply the pod:
```yaml
apiVersion: v1
kind: Pod
metadata:
  name: test-pod
  namespace: default
spec:
  securityContext:
    seccompProfile:
      type: Localhost
      localhostProfile: operator/default/profile1.json
  containers:
    - name: test-container
      image: nginx
```
5. Remove the pod
6. Remove the profile

Is this reproducible for you? Can you share the output of `kubectl describe sp …`? Thank you!
