### ISSUE TITLE
Unable to create ResourceQuota for SecurityProfilesOperatorDaemon

### ISSUE THREAD

**Issue by helenabutowatcisco** [kubernetes-sigs/security-profiles-operator#858]
#### What happened:
Tried to create a ResourceQuota for instance of the SecurityProfilesOperatorDaemon CRD. Instead, the following error was returned:
```
The ResourceQuota "test-object-counts" is invalid: spec.hard[count/securityprofilesoperatordaemons.security-profiles-operator.x-k8s.io]: Invalid value: "count/securityprofilesoperatordaemons.security-profiles-operator.x-k8s.io": name part must be no more than 63 characters
```

#### What you expected to happen:
The ResourceQuota is created.

#### How to reproduce it (as minimally and precisely as possible):
`kubectl create -f` the following:
```
apiVersion: v1
kind: ResourceQuota
metadata:
  name: test-object-counts
spec:
  hard:
    count/securityprofilesoperatordaemons.security-profiles-operator.x-k8s.io: 100
```

#### Anything else we need to know?:
Could a shorter name be used for the CRD?

#### Environment:

- Cloud provider or hardware configuration: EKS with a Kubernetes 1.20 control plane
- OS (e.g: `cat /etc/os-release`): n/a
- Kernel (e.g. `uname -a`): n/a
- Others: kubectl version 1.23.5
